// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://repqfbxmiqcnofkmtivi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJlcHFmYnhtaXFjbm9ma210aXZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5NjU1NTgsImV4cCI6MjA3MjU0MTU1OH0.wfysRHzuj7h3U84ylvqqFHm_YXHZe4OOjsnj5IH1xvw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});